### ISSUE TITLE
Example VPC Intra-inspection does not match the diagram

### ISSUE THREAD

**Issue by jlamande** [aws-ia/terraform-aws-networkfirewall#4]
I am looking for a terraform deployment of the VPC intra-inspection model with NAT Gateway and particularly how to setup the public subnet route table (overriding the default behavior of route table from `vpc cidr = local` to `vpc cidr = vpce firewall` seems a bit tricky in terraform).

Unfortunately the contents of the [VPC Intra-inspection example](https://github.com/aws-ia/terraform-aws-networkfirewall/blob/main/examples/intra_vpc_inspection/README.md) does not match the attached diagram. No public subnet, No Nat Gateway and so no configuration of the public subnet route table.

**Comment by pablo19sc** [comment]
Hi @jlamande! I updated this module, and also I re-wrote the examples - I removed also the diagrams to avoid confusion. What is exactly what you want to achieve?
